# Generated by Django 3.1.3 on 2020-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='heroes_profile'),
        ),
    ]
